version: '3.8'

services:
  db:
    image: postgres:15
    container_name: pulsetrack-db
    restart: always
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: pulsetrack
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pulsetrack-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pulsetrack-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - pulsetrack-network

volumes:
  postgres_data:

networks:
  pulsetrack-network:
